name: C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build

    - name: Build the project
      run: cmake --build build

    - name: Run Unit Tests
      working-directory: build
      run: ctest --output-on-failure